name: Local CI Build Test

on:
  schedule:
    - cron: "0 13 * * *"  # 6:30 PM IST
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_copy:
    runs-on: ubuntu-latest

    steps:
        - name: Install Dependencies
          working-directory: ./my-scheduled-app
          run: npm ci

        - name: Build Project
          working-directory: ./my-scheduled-app
          run: npm run build

        - name: List build folder
          working-directory: ./my-scheduled-app
          run: ls -R

        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: next-build
            path: my-scheduled-app/.next