name: Local CI Build Test

on:
  schedule:
    - cron: "0 13 * * *"  # 6:30 PM IST
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_copy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 20

        - name: Install Dependencies
          working-directory: ./next-js/my-scheduled-app
          run: npm ci

        - name: Build Project
          working-directory: ./next-js/my-scheduled-app
          run: npm run build

        - name: List build folder
          working-directory: ./next-js/my-scheduled-app
          run: ls -R

        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
              name: next-build
              path: next-js/my-scheduled-app/.next
